name: Terraform merging Statergies

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{secrets.ACCOUNT_ID}}:role/${{secrets.ROLE_NAME}}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan
        if: github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/feature/')
        run: terraform plan -var-file="dev.tfvars" -out=tfplan

      - name: Show Plan
        run: terraform show -json tfplan > tfplan.json
  
      - name: Comment Plan on PR
        uses: marrtins/terraform-comment@v1.1
        with:
          tf-plan-json: tfplan.json
          github-token: ${{ secrets.ACCESS_GITHUB_TOKEN }}
